### ISSUE TITLE
Option for changing semester in Attendance and Time-Table screen

### ISSUE THREAD

**Issue by TheGuyDangerous** [chaudharydeepanshu/mini_vtop#3]
<img src="https://user-images.githubusercontent.com/78858516/200315585-d073c17b-f2c1-4fc9-bbba-75b5f9d7a152.png" width="30%"></img>
<img src="https://user-images.githubusercontent.com/78858516/200315635-073e57ed-85e8-4909-ad94-6769c32f0f89.png" width="30%"></img>

Here are the screenshot references for better understanding.
The Time Table page and Attendance page are returning no output.
Rest working perfectly.

**Comment by chaudharydeepanshu** [comment]
Hey, thank you for reporting the issue. Can you please tell me your timeTableID which you can find by following the image below: 
![image](https://user-images.githubusercontent.com/85361211/200318263-a3d67762-92f5-4fd5-9087-269754c30eed.png)

Edit: Tell me your current semester timeTableID.

**Comment by TheGuyDangerous** [comment]
Wow , that was a quick reply !!

Here :
![image](https://user-images.githubusercontent.com/78858516/200329806-f391aecf-ef44-4fe1-8ce7-691df3daf178.png)

To be more specific - 

`<option value="BL2022235">Winter Semester 2022-23 - BPL</option>`

Would it be possible for you to add a multiple item drop down list (each item containing the timetableID for the semestername for students to choose from.. as it would be a more efficient solution to this 🤔)

**Comment by chaudharydeepanshu** [comment]
Hey, thank you for providing the details. By mistake, I used to assume that the identity of the semester was the same for everybody which was a wrong assumption. 

But now as you suggested a drop-down approach I think I can do it like this:-

- Add a settings screen in the drawer.
- Then Add an option to choose the timetable semester and attendance semester from drop downs in the setting screen.

Let me know what you think about that.

**Comment by TheGuyDangerous** [comment]
A question tho..

Didn't you already had this in your v1 deprecated ?🤔
![Screenshot_2022_1108_133441](https://user-images.githubusercontent.com/78858516/200508892-49f7b3e7-070d-47a0-a162-df54d48024cf.jpg)
and -
![Screenshot_2022_1108_134025](https://user-images.githubusercontent.com/78858516/200509641-6d67d0f7-98e3-4bea-97bd-8609f2eeb0a4.jpg)

**Comment by chaudharydeepanshu** [comment]
Yeah, I had it in v1 but I didn't maintain it as the code was unmaintainable(no state management approach) and the UI was not suitable for smaller devices. And I created v1 for the VIT Projects prototype that's why it was never intended for public release.

But I liked the project so I recreated it with better knowledge and tools. And then I uploaded it to the play store as a few of my friends also wanted to use it.
I did cut features but overall the second version is maintainable, doesn't have unexpected crashes, reports errors, supports cached mode, and the UI is much better.

**Comment by TheGuyDangerous** [comment]
Fascinating !!
Guess this feature was not worth cutting ;)   would love you to add it again.

As for the story side of it , someone sent me the v1 apk months ago and .. well I liked the idea , and had some improvements in mind myself, so tried to decompile the app for the source code (as I could'nt find any links to this repository in the app itself.).. then found that the code was in written in dart... (and reverse engineered files are made for kotlin).

Then again , recently , the idea of creating a fully functional mini vtop struck my mind again (for this semester's project exhibition), before I found your github repo through a simple google search on the topic. (Also the package name of the app gave it away).

Well now I'd have to think of something else 😜 as this one's pretty close to perfect.

**Comment by chaudharydeepanshu** [comment]
Hey @TheGuyDangerous,

Sorry, for the delayed response. I've been busy with a lot of other tasks lately, but I didn't want to leave this issue unresolved.

I'm happy to say that I've managed to add semester selection to both the attendance and timetable sections. And I've also included the option to set a default semester for these sections separately. You can pull the latest code from this repository to see how it works for you. Note: This fix has not yet been released on the Play Store, but I will be doing that soon.

I'm glad you found the repository. Please let me know if you have any other feedback or suggestions.
As for your project exhibition, I'm interested to hear what idea you ultimately decided on 😄. Feel free to share any details you'd like.

<img src="https://user-images.githubusercontent.com/85361211/210904772-4b45fbd1-e4cb-40c0-a8a1-71b7b9909a4b.jpeg"  height="600" />

**Comment by chaudharydeepanshu** [comment]
New update with the above fix is available in Play Store.
